### ISSUE TITLE
Urgent: Background color in oppgaver/scratch removed in print

### ISSUE THREAD

**Issue by niclan** [kodeklubben/codeclub-viewer#688]
This has been observed in all scratch assignments when printing.  All background color shown in this screenshot is removed (fraom scratch/flaksefugl) 
![flaksefugl-mssing-markup](https://user-images.githubusercontent.com/1439524/98175649-4814a500-1ef7-11eb-8d96-2a2c76bff30b.png)

The purple and orange text backgroung in the second and third checkbox items is rather vital to the kids to be able to understand what to look for in the code on their screens.

This seems to be due to this CSS:
```css
@media print
main.807a43.css:227
*, *:before, *:after {
    color: #000 !important;
    text-shadow: none !important;
    background: transparent !important;
    box-shadow: none !important;
}
```
whose origin I'm not quite able to trace in the codeclub-viewer source code.  When using the inspector to disable the `background: transparent !important;` line the print is again with colors.
